"""Migrated to canonical tollgate.anomaly_detector. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./anomaly_detector.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/anomaly_detector.py.
"""

from tollgate.anomaly_detector import *  # noqa: F401, F403
