"""Migrated to canonical tollgate.approvals. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./approvals.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/approvals.py.
"""

from tollgate.approvals import *  # noqa: F401, F403
