"""Migrated to canonical tollgate.audit_viewer. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./audit_viewer.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/audit_viewer.py.
"""

from tollgate.audit_viewer import *  # noqa: F401, F403
