"""Migrated to canonical tollgate.audit. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./audit.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/audit.py.
"""

from tollgate.audit import *  # noqa: F401, F403
