"""Migrated to canonical tollgate.cache. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./cache.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/cache.py.
"""

from tollgate.cache import *  # noqa: F401, F403
