"""Migrated to canonical tollgate.circuit_breaker. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./circuit_breaker.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/circuit_breaker.py.
"""

from tollgate.circuit_breaker import *  # noqa: F401, F403
