"""Migrated to canonical tollgate.cli. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./cli.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/cli.py.
"""

from tollgate.cli import *  # noqa: F401, F403
