"""Migrated to canonical tollgate.context_monitor. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./context_monitor.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/context_monitor.py.
"""

from tollgate.context_monitor import *  # noqa: F401, F403
