"""Migrated to canonical tollgate.exceptions. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./exceptions.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/exceptions.py.
"""

from tollgate.exceptions import *  # noqa: F401, F403
