"""Migrated to canonical tollgate.grants. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./grants.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/grants.py.
"""

from tollgate.grants import *  # noqa: F401, F403
