"""Migrated to canonical tollgate.manifest_signing. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./manifest_signing.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/manifest_signing.py.
"""

from tollgate.manifest_signing import *  # noqa: F401, F403
