"""Migrated to canonical tollgate.network_guard. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./network_guard.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/network_guard.py.
"""

from tollgate.network_guard import *  # noqa: F401, F403
