"""Migrated to canonical tollgate.otel. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./otel.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/otel.py.
"""

from tollgate.otel import *  # noqa: F401, F403
