"""Migrated to canonical tollgate.playground. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./playground.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/playground.py.
"""

from tollgate.playground import *  # noqa: F401, F403
