"""Migrated to canonical tollgate.policy_testing. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./policy_testing.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/policy_testing.py.
"""

from tollgate.policy_testing import *  # noqa: F401, F403
