"""Migrated to canonical tollgate.policy. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./policy.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/policy.py.
"""

from tollgate.policy import *  # noqa: F401, F403
