"""Migrated to canonical tollgate.rate_limiter. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./rate_limiter.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/rate_limiter.py.
"""

from tollgate.rate_limiter import *  # noqa: F401, F403
