"""Migrated to canonical tollgate.registry. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./registry.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/registry.py.
"""

from tollgate.registry import *  # noqa: F401, F403
