"""Migrated to canonical tollgate.reputation. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./reputation.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/reputation.py.
"""

from tollgate.reputation import *  # noqa: F401, F403
