"""Migrated to canonical tollgate.slo. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./slo.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/slo.py.
"""

from tollgate.slo import *  # noqa: F401, F403
