"""Migrated to canonical tollgate.telemetry. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./telemetry.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/telemetry.py.
"""

from tollgate.telemetry import *  # noqa: F401, F403
