"""Migrated to canonical tollgate.tower. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./tower.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/tower.py.
"""

from tollgate.tower import *  # noqa: F401, F403
