"""Migrated to canonical tollgate.types. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./types.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/types.py.
"""

from tollgate.types import *  # noqa: F401, F403
