"""Migrated to canonical tollgate.verification. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./verification.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/verification.py.
"""

from tollgate.verification import *  # noqa: F401, F403
