"""Migrated to canonical tollgate.workflow. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./workflow.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/workflow.py.
"""

from tollgate.workflow import *  # noqa: F401, F403
