"""Migrated to canonical tollgate.tenancy.quotas. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./tenancy/quotas.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/tenancy/quotas.py.
"""

from tollgate.tenancy.quotas import *  # noqa: F401, F403
