"""Migrated to canonical tollgate.interceptors.base. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./interceptors/base.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/interceptors/base.py.
"""

from tollgate.interceptors.base import *  # noqa: F401, F403
