"""Migrated to canonical tollgate.interceptors.langchain. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./interceptors/langchain.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/interceptors/langchain.py.
"""

from tollgate.interceptors.langchain import *  # noqa: F401, F403
