"""Migrated to canonical tollgate.interceptors.openai. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./interceptors/openai.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/interceptors/openai.py.
"""

from tollgate.interceptors.openai import *  # noqa: F401, F403
