"""Migrated to canonical tollgate.api.routes. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./api/routes.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/api/routes.py.
"""

from tollgate.api.routes import *  # noqa: F401, F403
