"""Migrated to canonical tollgate.api.server. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./api/server.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/api/server.py.
"""

from tollgate.api.server import *  # noqa: F401, F403
