"""
Foundry CLI — the command-line interface for the agent incubation platform.

Usage:
    foundry agent new <name>        Scaffold a new agent in the current directory
    foundry agent list              List all agents in a registry or directory
    foundry agent validate          Validate a manifest.yaml file
    foundry agent promote <stage>   Promote an agent to the next lifecycle stage
    foundry agent suspend           Suspend an agent (kill switch)
    foundry agent resume            Resume a suspended agent
    foundry registry submit         Prepare a manifest for registry PR submission
    foundry registry list           List all agents in the central registry
    foundry effects list            List all effects in the taxonomy
    foundry effects show <effect>   Show details for a specific effect
"""

import json
import sys
from pathlib import Path

import click
import yaml

# ─── Helpers ──────────────────────────────────────────────────────────────────

def _load_manifest_safe(path: Path):
    """Load manifest, printing a helpful error and exiting on failure."""
    from arc.core.manifest import load_manifest
    try:
        return load_manifest(path)
    except FileNotFoundError:
        click.echo(click.style(f"✗ No manifest found at: {path}", fg="red"), err=True)
        sys.exit(1)
    except ValueError as e:
        click.echo(click.style(f"✗ Invalid manifest: {e}", fg="red"), err=True)
        sys.exit(1)


MANIFEST_TEMPLATE = """\
# Agent Manifest — {name}
# Generated by: foundry agent new
# ─────────────────────────────────────────────────

agent_id: {name}
version: "0.1.0"
owner: your-team-name
description: >
  Describe what this agent does in 1–3 sentences. Be specific about
  the business problem it solves, who it helps, and how it acts.

lifecycle_stage: DISCOVER
environment: sandbox
status: active

# Your GitHub/GitLab repo that owns this agent's code.
team_repo: https://github.com/your-org/your-repo

# The version of agent-foundry this agent targets.
foundry_version: ">=0.1.0"

# Effects this agent is permitted to invoke.
# Start minimal — only add effects you actually need.
# See: foundry effects list
allowed_effects:
  - participant.data.read
  # - risk.score.compute
  # - intervention.draft
  # - audit.log.write

# Named data sources this agent may access via Gateway.
data_access:
  - participant.data

# Path to this agent's YAML policy file (relative to project root).
policy_path: examples/{name}/policy.yaml

# Success metrics — what "good" looks like after 30 days in production.
# Be measurable and specific. These are reviewed during Stage 5 governance.
success_metrics:
  - "TODO: define primary success metric"
  - "TODO: define secondary metric"

tags:
  - {name}
"""

POLICY_TEMPLATE = """\
# Policy overrides for: {name}
# ─────────────────────────────
# This file is layered on top of policies/financial_services/defaults.yaml.
# Only include rules that DIFFER from the defaults.
# Hard denies in defaults.yaml cannot be overridden here.
#
# Format:
#   rules:
#     - resource_type: <effect-value>
#       decision: ALLOW | ASK | DENY
#       reason: "Why this override exists"
#       when:
#         manifest_version: "{name}@*"

rules: []
  # Example override — tighten communication send to always require review:
  # - resource_type: "participant.communication.send"
  #   decision: ASK
  #   reason: "This agent sends high-frequency messages; always require batch review"
  #   when:
  #     manifest_version: "{name}@*"
"""

AGENT_TEMPLATE = '''\
"""
{name_title} — Agent Implementation

Built on agent-foundry BaseAgent. All tool calls go through
ControlTower for policy enforcement and audit logging.

Run this agent:
    python examples/{name}/agent.py
"""

import asyncio
import logging
from pathlib import Path

from arc.core.gateway import HttpGateway
from arc.core.observability import OutcomeTracker
from arc.core.effects import FinancialEffect
from arc.core import BaseAgent, load_manifest
from tollgate import (
    AutoApprover,
    ControlTower,
    JsonlAuditSink,
    YamlPolicyEvaluator,
)

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
logger = logging.getLogger(__name__)

POLICY_PATH = Path(__file__).parent / "policy.yaml"
MANIFEST_PATH = Path(__file__).parent / "manifest.yaml"


class {class_name}(BaseAgent):
    """
    {name_title}.

    TODO: Describe what this agent does step by step.
    """

    async def execute(self, **kwargs) -> dict:
        results = {{"processed": 0, "errors": 0}}

        # TODO: Implement agent logic using self.run_effect()
        # Example:
        # data = await self.gateway.fetch(DataRequest(source="...", params={{...}}))
        # result = await self.run_effect(
        #     effect=FinancialEffect.RISK_SCORE_COMPUTE,
        #     tool="my_tool",
        #     action="compute",
        #     params={{...}},
        #     intent_action="describe_action",
        #     intent_reason="Explain why this action is taken",
        # )

        logger.info("Run complete: %s", results)
        return results


def build_agent() -> {class_name}:
    """Wire up the agent with its policy, gateway, and tower."""
    manifest = load_manifest(MANIFEST_PATH)

    policy = YamlPolicyEvaluator(POLICY_PATH)
    approver = AutoApprover(default_outcome="approved")
    audit = JsonlAuditSink("audit.jsonl")
    tower = ControlTower(policy=policy, approver=approver, audit=audit)

    # TODO: replace with your real API base URL
    gateway = HttpGateway("https://your-internal-api.example.com")

    tracker = OutcomeTracker(path="outcomes.jsonl")

    return {class_name}(
        manifest=manifest,
        tower=tower,
        gateway=gateway,
        tracker=tracker,
    )


async def main():
    agent = build_agent()
    results = await agent.execute()
    print("\\nResults:", results)

    if agent.tracker:
        print("Outcomes:", agent.tracker.summary())


if __name__ == "__main__":
    asyncio.run(main())
'''


# ─── CLI Groups ───────────────────────────────────────────────────────────────

@click.group()
@click.version_option(package_name="agent-foundry")
def cli():
    """
    Foundry — the agent incubation platform.

    Build, validate, govern, and register AI agents for financial services.
    """


@cli.group()
def agent():
    """Commands for creating and managing individual agents."""


@cli.group()
def registry():
    """Commands for the central agent registry."""


@cli.group()
def effects():
    """Commands for browsing the financial effect taxonomy."""


# ─── foundry agent new ────────────────────────────────────────────────────────

@agent.command("new")
@click.argument("name")
@click.option("--dir", "output_dir", default=".", help="Directory to scaffold into (default: current dir)")
def agent_new(name: str, output_dir: str):
    """
    Scaffold a new agent directory.

    Creates NAME/manifest.yaml, NAME/policy.yaml, and NAME/agent.py
    pre-wired with the Foundry conventions and effect declarations.

    Example:
        foundry agent new fee-transparency
        foundry agent new market-risk-monitor --dir src/agents
    """
    # Sanitize name
    slug = name.lower().replace(" ", "-").replace("_", "-")
    class_name = "".join(w.title() for w in slug.split("-")) + "Agent"
    name_title = " ".join(w.title() for w in slug.split("-"))

    base = Path(output_dir) / slug
    if base.exists():
        click.echo(click.style(f"✗ Directory already exists: {base}", fg="red"), err=True)
        sys.exit(1)

    base.mkdir(parents=True)

    (base / "manifest.yaml").write_text(
        MANIFEST_TEMPLATE.format(name=slug)
    )
    (base / "policy.yaml").write_text(
        POLICY_TEMPLATE.format(name=slug)
    )
    (base / "agent.py").write_text(
        AGENT_TEMPLATE.format(
            name=slug,
            name_title=name_title,
            class_name=class_name,
        )
    )
    (base / "tests").mkdir()
    (base / "tests" / f"test_{slug.replace('-', '_')}.py").write_text(
        f'"""Tests for {name_title} agent."""\n\nimport pytest\n\n\n'
        f'# TODO: Add tests\n'
    )

    click.echo(click.style(f"✓ Scaffolded agent: {slug}/", fg="green"))
    click.echo(f"  {slug}/manifest.yaml  — declare effects and success metrics")
    click.echo(f"  {slug}/policy.yaml    — add any policy overrides")
    click.echo(f"  {slug}/agent.py       — implement your agent logic")
    click.echo(f"  {slug}/tests/         — write your tests")
    click.echo()
    click.echo(click.style("Next steps:", bold=True))
    click.echo(f"  1. Edit {slug}/manifest.yaml and set allowed_effects")
    click.echo(f"  2. Implement {class_name}.execute() in {slug}/agent.py")
    click.echo(f"  3. foundry agent validate {slug}/manifest.yaml")


# ─── foundry agent validate ───────────────────────────────────────────────────

@agent.command("validate")
@click.argument("manifest_path", default="manifest.yaml", required=False)
@click.option("--strict", is_flag=True, help="Fail on warnings (use in CI)")
def agent_validate(manifest_path: str, strict: bool):
    """
    Validate a manifest.yaml file.

    Checks that all required fields are present, all declared effects
    exist in the taxonomy, and all policy references are valid.

    Example:
        foundry agent validate
        foundry agent validate examples/retirement_trajectory/manifest.yaml
        foundry agent validate --strict  # for CI gates
    """
    from arc.core.effects import FinancialEffect, effect_meta
    from arc.core.manifest import AgentStatus

    path = Path(manifest_path)
    manifest = _load_manifest_safe(path)

    warnings = []
    errors = []

    # Check: status
    if manifest.status == AgentStatus.SUSPENDED:
        warnings.append("Agent status is 'suspended' — agent will not execute until resumed")
    if manifest.status == AgentStatus.DEPRECATED:
        warnings.append("Agent status is 'deprecated'")

    # Check: lifecycle stage vs environment
    from arc.core.lifecycle import LifecycleStage
    if manifest.lifecycle_stage == LifecycleStage.SCALE and manifest.environment != "production":
        warnings.append("Lifecycle stage is SCALE but environment is not 'production'")
    if manifest.lifecycle_stage in (LifecycleStage.DISCOVER, LifecycleStage.SHAPE) and manifest.environment == "production":
        errors.append("Production environment is not allowed before stage VALIDATE")

    # Check: effects exist in taxonomy
    for effect in manifest.allowed_effects:
        meta = effect_meta(effect)
        from arc.core.effects import DefaultDecision
        if meta.default_decision == DefaultDecision.DENY:
            errors.append(
                f"Effect '{effect.value}' has a hard DENY default — "
                f"it cannot be declared in allowed_effects"
            )

    # Check: policy path exists
    policy_path = Path(manifest.policy_path)
    if not policy_path.exists():
        # Also try relative to manifest directory
        alt_path = path.parent / "policy.yaml"
        if not alt_path.exists():
            warnings.append(f"Policy file not found: {manifest.policy_path}")

    # Check: success metrics
    if not manifest.success_metrics:
        errors.append("success_metrics must have at least one entry")
    for m in manifest.success_metrics:
        if m.startswith("TODO"):
            warnings.append(f"Success metric appears to be a placeholder: '{m}'")

    # Check: team_repo
    if not manifest.team_repo:
        warnings.append("team_repo is not set — recommended for registry submissions")

    # Print results
    click.echo(click.style(f"Validating: {path}", bold=True))
    click.echo(f"  Agent:    {manifest.agent_id} v{manifest.version}")
    click.echo(f"  Stage:    {manifest.lifecycle_stage.value}")
    click.echo(f"  Status:   {manifest.status.value}")
    click.echo(f"  Effects:  {len(manifest.allowed_effects)} declared")
    click.echo()

    for w in warnings:
        click.echo(click.style(f"  ⚠ {w}", fg="yellow"))

    for e in errors:
        click.echo(click.style(f"  ✗ {e}", fg="red"))

    if errors:
        click.echo()
        click.echo(click.style(f"✗ Validation failed — {len(errors)} error(s)", fg="red"))
        sys.exit(1)
    elif warnings and strict:
        click.echo()
        click.echo(click.style(f"✗ Strict mode: {len(warnings)} warning(s)", fg="red"))
        sys.exit(1)
    else:
        click.echo()
        click.echo(click.style("✓ Manifest is valid", fg="green"))
        if warnings:
            click.echo(f"  ({len(warnings)} warning(s) — run without --strict to allow)")


# ─── foundry agent list ───────────────────────────────────────────────────────

@agent.command("list")
@click.option("--dir", "search_dir", default=".", help="Root directory to search (default: current dir)")
@click.option("--format", "fmt", type=click.Choice(["table", "json"]), default="table")
def agent_list(search_dir: str, fmt: str):
    """
    List all agents found in a directory tree.

    Finds every manifest.yaml under the given directory and prints
    a summary table. Useful for browsing agents in a team repo or registry.

    Example:
        foundry agent list
        foundry agent list --dir examples
        foundry agent list --format json
    """
    from arc.core.manifest import load_manifest

    manifests = list(Path(search_dir).rglob("manifest.yaml"))
    if not manifests:
        click.echo("No agents found.")
        return

    agents = []
    for p in sorted(manifests):
        try:
            m = load_manifest(p)
            agents.append(m)
        except Exception:
            pass  # Skip invalid manifests silently in list

    if fmt == "json":
        click.echo(json.dumps([a.to_dict() for a in agents], indent=2))
        return

    # Table output
    col_w = [28, 10, 12, 11, 8]
    header = (
        f"{'AGENT':<{col_w[0]}} {'VERSION':<{col_w[1]}} "
        f"{'STAGE':<{col_w[2]}} {'STATUS':<{col_w[3]}} {'ENV':<{col_w[4]}}"
    )
    click.echo(click.style(header, bold=True))
    click.echo("─" * sum(col_w + [4]))

    for m in agents:
        status_color = {"active": "green", "suspended": "red", "deprecated": "yellow"}.get(
            m.status.value, "white"
        )
        row = (
            f"{m.agent_id:<{col_w[0]}} {m.version:<{col_w[1]}} "
            f"{m.lifecycle_stage.value:<{col_w[2]}} "
            f"{click.style(m.status.value, fg=status_color):<{col_w[3]+9}} "
            f"{m.environment:<{col_w[4]}}"
        )
        click.echo(row)

    click.echo()
    click.echo(f"{len(agents)} agent(s) found")


# ─── foundry agent promote ────────────────────────────────────────────────────

@agent.command("promote")
@click.argument("manifest_path", default="manifest.yaml", required=False)
@click.option("--to", "target_stage", required=False, help="Target stage (default: next stage)")
@click.option("--dry-run", is_flag=True, help="Show what would happen without writing")
def agent_promote(manifest_path: str, target_stage: str | None, dry_run: bool):
    """
    Promote an agent to the next lifecycle stage.

    Updates the lifecycle_stage field in the manifest.yaml and
    validates exit criteria for the current stage.

    Example:
        foundry agent promote
        foundry agent promote --to VALIDATE
        foundry agent promote --dry-run
    """
    from arc.core.lifecycle import LifecycleStage

    path = Path(manifest_path)
    manifest = _load_manifest_safe(path)

    stage_order = [s for s in LifecycleStage]
    current_idx = stage_order.index(manifest.lifecycle_stage)

    if target_stage:
        try:
            next_stage = LifecycleStage(target_stage.upper())
        except ValueError:
            valid = [s.value for s in LifecycleStage]
            click.echo(click.style(f"✗ Invalid stage '{target_stage}'. Must be one of: {valid}", fg="red"), err=True)
            sys.exit(1)
    else:
        if current_idx + 1 >= len(stage_order):
            click.echo(click.style("✗ Agent is already at the final stage (SCALE)", fg="yellow"))
            sys.exit(0)
        next_stage = stage_order[current_idx + 1]

    click.echo(f"Promoting: {manifest.agent_id}")
    click.echo(f"  {manifest.lifecycle_stage.value} → {next_stage.value}")

    if next_stage == LifecycleStage.SCALE:
        click.echo()
        click.echo(click.style("  ⚠ Promoting to SCALE sets environment to 'production'", fg="yellow"))

    if dry_run:
        click.echo()
        click.echo(click.style("Dry run — no changes written", fg="yellow"))
        return

    # Read raw YAML and update in-place
    with open(path) as f:
        content = f.read()

    content = content.replace(
        f"lifecycle_stage: {manifest.lifecycle_stage.value}",
        f"lifecycle_stage: {next_stage.value}",
    )

    if next_stage == LifecycleStage.SCALE:
        content = content.replace("environment: sandbox", "environment: production")

    with open(path, "w") as f:
        f.write(content)

    click.echo(click.style(f"✓ Promoted to {next_stage.value}", fg="green"))
    if next_stage == LifecycleStage.GOVERN:
        click.echo()
        click.echo("  Next step: open a PR to the agent-registry repo for compliance review")
        click.echo("  Run: foundry registry submit")


# ─── foundry agent suspend / resume ───────────────────────────────────────────

@agent.command("suspend")
@click.argument("manifest_path", default="manifest.yaml", required=False)
@click.option("--reason", required=True, help="Reason for suspension (required for audit trail)")
def agent_suspend(manifest_path: str, reason: str):
    """
    Suspend an agent (kill switch).

    Sets status: suspended in the manifest. The agent will be blocked
    from executing any effects until it is resumed.

    Example:
        foundry agent suspend --reason "Unexpected communication volume spike"
    """
    path = Path(manifest_path)
    manifest = _load_manifest_safe(path)

    from arc.core.manifest import AgentStatus
    if manifest.status == AgentStatus.SUSPENDED:
        click.echo(click.style(f"Agent '{manifest.agent_id}' is already suspended", fg="yellow"))
        return

    with open(path) as f:
        content = f.read()

    if f"status: {manifest.status.value}" in content:
        content = content.replace(f"status: {manifest.status.value}", "status: suspended")
    else:
        # Status not in file yet — add it
        content = content.replace(
            f"lifecycle_stage: {manifest.lifecycle_stage.value}",
            f"lifecycle_stage: {manifest.lifecycle_stage.value}\nstatus: suspended",
        )

    with open(path, "w") as f:
        f.write(content)

    click.echo(click.style(f"✓ Agent '{manifest.agent_id}' suspended", fg="red", bold=True))
    click.echo(f"  Reason: {reason}")
    click.echo(f"  To resume: foundry agent resume {manifest_path}")


@agent.command("resume")
@click.argument("manifest_path", default="manifest.yaml", required=False)
def agent_resume(manifest_path: str):
    """Resume a suspended agent."""
    path = Path(manifest_path)
    manifest = _load_manifest_safe(path)

    from arc.core.manifest import AgentStatus
    if manifest.status != AgentStatus.SUSPENDED:
        click.echo(click.style(f"Agent '{manifest.agent_id}' is not suspended (status: {manifest.status.value})", fg="yellow"))
        return

    with open(path) as f:
        content = f.read()

    content = content.replace("status: suspended", "status: active")
    with open(path, "w") as f:
        f.write(content)

    click.echo(click.style(f"✓ Agent '{manifest.agent_id}' resumed", fg="green"))


# ─── foundry registry submit ──────────────────────────────────────────────────

@registry.command("submit")
@click.argument("manifest_path", default="manifest.yaml", required=False)
@click.option("--registry-dir", default=None, help="Path to local agent-registry checkout")
def registry_submit(manifest_path: str, registry_dir: str | None):
    """
    Prepare a manifest for submission to the central agent-registry.

    Validates the manifest, then either copies it to a local registry
    checkout (if --registry-dir is provided) or prints the PR checklist.

    Example:
        foundry registry submit
        foundry registry submit --registry-dir ../agent-registry
    """
    path = Path(manifest_path)
    manifest = _load_manifest_safe(path)

    # Run validation
    from arc.core.effects import effect_meta, DefaultDecision
    errors = []
    for effect in manifest.allowed_effects:
        meta = effect_meta(effect)
        if meta.default_decision == DefaultDecision.DENY:
            errors.append(f"Hard-denied effect: {effect.value}")

    if errors:
        click.echo(click.style("✗ Manifest cannot be submitted:", fg="red"))
        for e in errors:
            click.echo(f"  {e}")
        sys.exit(1)

    if registry_dir:
        import shutil
        dest = Path(registry_dir) / "registry" / manifest.agent_id
        dest.mkdir(parents=True, exist_ok=True)
        shutil.copy(path, dest / "manifest.yaml")
        click.echo(click.style(f"✓ Manifest copied to {dest}", fg="green"))
        click.echo("  Open a PR against the agent-registry repo to complete registration")
    else:
        click.echo(click.style("Registry submission checklist:", bold=True))
        click.echo()
        click.echo(f"  Agent:  {manifest.agent_id} v{manifest.version}")
        click.echo(f"  Owner:  {manifest.owner}")
        click.echo(f"  Stage:  {manifest.lifecycle_stage.value}")
        click.echo()
        click.echo("  PR steps:")
        click.echo("  1. Fork/clone: https://github.com/ravi-labs/agent-registry")
        click.echo(f"  2. Copy manifest: cp {path} registry/{manifest.agent_id}/manifest.yaml")
        click.echo(f"  3. git checkout -b register/{manifest.agent_id}")
        click.echo("  4. git add . && git commit -m 'Register {}'".format(manifest.agent_id))
        click.echo("  5. Open PR — compliance officer will review effects and policy")


# ─── foundry registry list ────────────────────────────────────────────────────

@registry.command("list")
@click.option("--registry-dir", default=None, help="Path to local agent-registry checkout")
@click.option("--format", "fmt", type=click.Choice(["table", "json"]), default="table")
def registry_list(registry_dir: str | None, fmt: str):
    """
    List all agents registered in the central registry.

    Reads from a local agent-registry checkout, or from registry.yaml
    if it exists.

    Example:
        foundry registry list --registry-dir ../agent-registry
    """
    if registry_dir is None:
        # Try relative paths
        for candidate in ["../agent-registry", "../../agent-registry"]:
            if Path(candidate).exists():
                registry_dir = candidate
                break

    if registry_dir is None or not Path(registry_dir).exists():
        click.echo(click.style(
            "No registry found. Provide --registry-dir pointing to a local agent-registry checkout.",
            fg="yellow"
        ))
        click.echo("  Clone: git clone https://github.com/ravi-labs/agent-registry")
        return

    # Load from registry.yaml if present, else scan manifests
    registry_yaml = Path(registry_dir) / "registry.yaml"
    if registry_yaml.exists():
        with open(registry_yaml) as f:
            data = yaml.safe_load(f)
        entries = data.get("agents", [])
        if fmt == "json":
            click.echo(json.dumps(entries, indent=2))
            return
        click.echo(click.style(f"Central Registry  ({len(entries)} agents)", bold=True))
        click.echo("─" * 72)
        for e in entries:
            status_color = {"active": "green", "suspended": "red", "deprecated": "yellow"}.get(
                e.get("status", "active"), "white"
            )
            click.echo(
                f"  {e['agent_id']:<28} "
                f"{e.get('version', ''):<10} "
                f"{e.get('lifecycle_stage', ''):<12} "
                f"{click.style(e.get('status', 'active'), fg=status_color)}"
            )
    else:
        # Scan manifests
        from arc.core.manifest import load_manifest
        manifests = sorted(Path(registry_dir).rglob("manifest.yaml"))
        agents = []
        for p in manifests:
            try:
                agents.append(load_manifest(p))
            except Exception:
                pass
        if fmt == "json":
            click.echo(json.dumps([a.to_dict() for a in agents], indent=2))
            return
        click.echo(click.style(f"Central Registry  ({len(agents)} agents)", bold=True))
        click.echo("─" * 72)
        for m in agents:
            click.echo(f"  {m.agent_id:<28} {m.version:<10} {m.lifecycle_stage.value:<12} {m.owner}")


# ─── foundry effects list ─────────────────────────────────────────────────────

@effects.command("list")
@click.option("--tier", type=int, default=None, help="Filter by tier (1–6)")
@click.option("--format", "fmt", type=click.Choice(["table", "json"]), default="table")
def effects_list(tier: int | None, fmt: str):
    """
    List all effects in the financial services taxonomy.

    Effects are the atomic actions an agent can take. Every effect
    maps to a policy decision (ALLOW/ASK/DENY) and an audit tier.

    Example:
        foundry effects list
        foundry effects list --tier 4
        foundry effects list --format json
    """
    from arc.core.effects import FinancialEffect, EffectTier, effect_meta

    all_effects = list(FinancialEffect)
    if tier is not None:
        try:
            filter_tier = EffectTier(tier)
        except ValueError:
            click.echo(click.style(f"✗ Invalid tier {tier}. Must be 1–6.", fg="red"), err=True)
            sys.exit(1)
        all_effects = [e for e in all_effects if effect_meta(e).tier == filter_tier]

    if fmt == "json":
        data = [
            {
                "effect": e.value,
                "tier": effect_meta(e).tier.value,
                "tier_name": effect_meta(e).tier.name,
                "default_decision": effect_meta(e).default_decision.value,
                "requires_human_review": effect_meta(e).requires_human_review,
                "description": effect_meta(e).description,
            }
            for e in all_effects
        ]
        click.echo(json.dumps(data, indent=2))
        return

    tier_names = {1: "Data Access", 2: "Computation", 3: "Draft", 4: "Output", 5: "Persistence", 6: "System Control"}
    current_tier = None

    for effect in all_effects:
        meta = effect_meta(effect)
        if meta.tier.value != current_tier:
            current_tier = meta.tier.value
            click.echo()
            click.echo(click.style(
                f"  Tier {current_tier} — {tier_names[current_tier]}",
                bold=True, underline=True
            ))

        decision_color = {"ALLOW": "green", "ASK": "yellow", "DENY": "red"}.get(
            meta.default_decision.value, "white"
        )
        review_flag = " ★" if meta.requires_human_review else ""
        click.echo(
            f"    {effect.value:<42} "
            f"[{click.style(meta.default_decision.value, fg=decision_color):<5}] "
            f"{review_flag}"
        )

    click.echo()
    click.echo(f"  {len(all_effects)} effects  |  ★ = requires human review")
    click.echo("  Run: foundry effects show <effect> for details")


@effects.command("show")
@click.argument("effect_name")
def effects_show(effect_name: str):
    """
    Show full details for a specific effect.

    Example:
        foundry effects show participant.communication.send
        foundry effects show compliance.finding.emit.high
    """
    from arc.core.effects import FinancialEffect, effect_meta

    try:
        effect = FinancialEffect(effect_name)
    except ValueError:
        click.echo(click.style(f"✗ Unknown effect: '{effect_name}'", fg="red"), err=True)
        click.echo("  Run: foundry effects list")
        sys.exit(1)

    meta = effect_meta(effect)
    decision_color = {"ALLOW": "green", "ASK": "yellow", "DENY": "red"}.get(
        meta.default_decision.value, "white"
    )

    tier_names = {1: "Data Access", 2: "Computation", 3: "Draft", 4: "Output", 5: "Persistence", 6: "System Control"}

    click.echo()
    click.echo(click.style(f"Effect: {effect.value}", bold=True))
    click.echo(f"  Tier:              {meta.tier.value} — {tier_names[meta.tier.value]}")
    click.echo(f"  Default decision:  {click.style(meta.default_decision.value, fg=decision_color)}")
    click.echo(f"  Tollgate base:     {meta.base_effect.value}")
    click.echo(f"  Human review:      {'Yes ★' if meta.requires_human_review else 'No'}")
    click.echo(f"  Audit required:    {'Yes' if meta.audit_required else 'No'}")
    click.echo()
    click.echo(f"  Description: {meta.description}")
    click.echo()

    if meta.default_decision.value == "DENY":
        click.echo(click.style(
            "  ⚠ This effect is hard-denied. It cannot be declared in any agent manifest.",
            fg="red"
        ))
    elif meta.requires_human_review:
        click.echo(click.style(
            "  ★ This effect goes to the human review queue before execution.",
            fg="yellow"
        ))


# ─── foundry deploy ───────────────────────────────────────────────────────────

@cli.group()
def deploy():
    """Package and deploy agents to AWS Lambda, ECS Fargate, or Bedrock Agent Core."""


@deploy.command("schema")
@click.argument("manifest_path", default="manifest.yaml")
@click.option("--output", "-o", default=None, help="Write schema to this file (default: stdout)")
@click.option("--upload-to-s3", default=None, help="s3://bucket/key — upload schema to S3")
def deploy_schema(manifest_path: str, output: str | None, upload_to_s3: str | None):
    """
    Generate an OpenAPI 3.0 Action Group schema for Bedrock Agent Core.

    Derives the schema from the agent manifest's declared effects.
    Tier 4+ effects (Output, Persistence, System) become API operations.

    Example:
        foundry deploy schema
        foundry deploy schema --output schema.json
        foundry deploy schema --upload-to-s3 s3://my-bucket/agents/watchdog/schema.json
    """
    import json as _json

    path = Path(manifest_path)
    manifest = _load_manifest_safe(path)

    try:
        from arc.runtime.deploy.bedrock import generate_action_schema, upload_schema_to_s3
    except ImportError:
        click.echo(click.style(
            "✗ AWS extras not installed. Run: pip install 'agent-foundry[aws]'", fg="red"
        ), err=True)
        sys.exit(1)

    schema = generate_action_schema(manifest)
    schema_json = _json.dumps(schema, indent=2)

    if upload_to_s3:
        if not upload_to_s3.startswith("s3://"):
            click.echo(click.style("✗ --upload-to-s3 must be an s3:// URI", fg="red"), err=True)
            sys.exit(1)
        parts = upload_to_s3[5:].split("/", 1)
        bucket, key = parts[0], parts[1] if len(parts) > 1 else "schema.json"
        uri = upload_schema_to_s3(schema, bucket, key)
        click.echo(click.style(f"✓ Schema uploaded to {uri}", fg="green"))
    elif output:
        Path(output).write_text(schema_json)
        click.echo(click.style(f"✓ Schema written to {output}", fg="green"))
    else:
        click.echo(schema_json)

    op_count = len(schema.get("paths", {}))
    if not upload_to_s3:
        click.echo(
            click.style(f"\n  {op_count} operations generated from {manifest.agent_id}", fg="cyan"),
            err=True,
        )


@deploy.command("package")
@click.argument("manifest_path", default="manifest.yaml")
@click.option("--target", type=click.Choice(["lambda", "ecs", "bedrock"]), default="ecs")
def deploy_package(manifest_path: str, target: str):
    """
    Show packaging instructions for the specified deployment target.

    Example:
        foundry deploy package --target ecs
        foundry deploy package --target bedrock
        foundry deploy package --target lambda
    """
    path = Path(manifest_path)
    manifest = _load_manifest_safe(path)

    click.echo(click.style(f"Deploy: {manifest.agent_id} → {target.upper()}", bold=True))
    click.echo()

    if target == "lambda":
        click.echo("  1. Build the Lambda deployment package:")
        click.echo(f"     pip install 'agent-foundry[aws]' -t ./package/")
        click.echo(f"     cp -r src/ ./package/")
        click.echo(f"     cp manifest.yaml policy.yaml policies/ ./package/")
        click.echo(f"     cd package && zip -r ../function.zip .")
        click.echo()
        click.echo("  2. In your handler.py:")
        click.echo("     from arc.runtime.deploy.lambda_handler import make_handler")
        click.echo(f"     from your_module import {manifest.agent_id.replace('-', '_').title().replace('_', '')}Agent")
        click.echo("     handler = make_handler(YourAgentClass)")
        click.echo()
        click.echo("  3. Set Lambda handler to: handler.handler")

    elif target == "ecs":
        click.echo("  1. Build the container image:")
        click.echo(f"     docker build -t {manifest.agent_id}:latest \\")
        click.echo(f"       --build-arg AGENT_MODULE=your_module \\")
        click.echo(f"       --build-arg AGENT_CLASS=YourAgentClass \\")
        click.echo(f"       -f deploy/Dockerfile .")
        click.echo()
        click.echo("  2. Push to ECR:")
        click.echo(f"     aws ecr create-repository --repository-name {manifest.agent_id}")
        click.echo(f"     docker tag {manifest.agent_id}:latest <ECR_URI>/{manifest.agent_id}:latest")
        click.echo(f"     docker push <ECR_URI>/{manifest.agent_id}:latest")
        click.echo()
        click.echo("  3. Register ECS task def:")
        click.echo("     Edit deploy/ecs-task-def.json with your values")
        click.echo("     aws ecs register-task-definition --cli-input-json file://ecs-task-def.json")

    elif target == "bedrock":
        from arc.core.lifecycle import LifecycleStage
        if manifest.lifecycle_stage not in (LifecycleStage.GOVERN, LifecycleStage.SCALE):
            click.echo(click.style(
                f"  ⚠ Bedrock Agent Core is recommended for GOVERN/SCALE stage agents only.",
                fg="yellow"
            ))
            click.echo(f"    Current stage: {manifest.lifecycle_stage.value}")
            click.echo()

        click.echo("  1. Generate Action Group schema:")
        click.echo(f"     arc deploy schema --upload-to-s3 s3://my-bucket/agents/{manifest.agent_id}/schema.json")
        click.echo()
        click.echo("  2. Deploy Lambda function (see --target lambda)")
        click.echo()
        click.echo("  3. Register in Bedrock Agent Core:")
        click.echo("     See deploy/bedrock-agent-core.md for full setup")
        click.echo()
        click.echo(click.style(
            "  Note: Tollgate policy enforcement runs inside your Lambda —\n"
            "  Bedrock cannot bypass ERISA/DOL policy rules.",
            fg="cyan"
        ))


@deploy.command("register")
@click.argument("manifest_path", default="manifest.yaml")
@click.option("--lambda-arn",       required=True,  help="ARN of the Lambda function for the action group")
@click.option("--role-arn",         required=True,  help="ARN of the IAM role Bedrock will assume")
@click.option("--schema-bucket",    required=True,  help="S3 bucket for the OpenAPI schema")
@click.option("--schema-key",       default=None,   help="S3 key for schema (default: agents/<agent_id>/schema.json)")
@click.option("--model",            default="anthropic.claude-3-5-sonnet-20241022-v2:0",
              help="Bedrock foundation model ID")
@click.option("--alias",            default="production", help="Agent alias name (default: production)")
@click.option("--no-alias",         is_flag=True,   default=False, help="Skip alias creation")
@click.option("--region",           default=None,   help="AWS region (default: from environment)")
@click.option("--dry-run",          is_flag=True,   default=False, help="Print what would happen without calling AWS")
def deploy_register(
    manifest_path: str,
    lambda_arn: str,
    role_arn: str,
    schema_bucket: str,
    schema_key: str | None,
    model: str,
    alias: str,
    no_alias: bool,
    region: str | None,
    dry_run: bool,
):
    """
    Register or update an agent in Amazon Bedrock Agent Core.

    This command:
      1. Generates the OpenAPI Action Group schema from the manifest
      2. Uploads it to S3
      3. Creates (or updates) the Bedrock Agent
      4. Associates the Lambda function as an Action Group
      5. Prepares the agent (DRAFT → PREPARED)
      6. Creates a stable alias

    Example:
        foundry deploy register \\
            --lambda-arn arn:aws:lambda:us-east-1:123:function:fiduciary-watchdog \\
            --role-arn arn:aws:iam::123:role/foundry-bedrock-fiduciary-watchdog-role \\
            --schema-bucket my-foundry-bucket
    """
    import json as _json

    path     = Path(manifest_path)
    manifest = _load_manifest_safe(path)

    try:
        from arc.runtime.deploy.bedrock import generate_action_schema, register_bedrock_agent
    except ImportError:
        click.echo(click.style(
            "✗ AWS extras not installed. Run: pip install 'agent-foundry[aws]'", fg="red"
        ), err=True)
        sys.exit(1)

    from arc.core.lifecycle import LifecycleStage
    if manifest.lifecycle_stage not in (LifecycleStage.GOVERN, LifecycleStage.SCALE):
        click.echo(click.style(
            f"  ⚠  Bedrock Agent Core is recommended for GOVERN/SCALE stage agents.\n"
            f"     Current stage: {manifest.lifecycle_stage.value}",
            fg="yellow",
        ))

    _schema_key = schema_key or f"agents/{manifest.agent_id}/schema.json"
    schema = generate_action_schema(manifest)
    op_count = len(schema.get("paths", {}))

    click.echo(click.style(f"Registering: {manifest.agent_id} @ {manifest.version}", bold=True))
    click.echo(f"  Lambda ARN:     {lambda_arn}")
    click.echo(f"  IAM role:       {role_arn}")
    click.echo(f"  Schema:         s3://{schema_bucket}/{_schema_key}  ({op_count} operations)")
    click.echo(f"  Model:          {model}")
    click.echo(f"  Alias:          {alias if not no_alias else '(none)'}")
    click.echo()

    if dry_run:
        click.echo(click.style("  [dry-run] No AWS calls made.", fg="yellow"))
        click.echo()
        click.echo("Schema preview:")
        click.echo(_json.dumps(schema, indent=2)[:2000])
        return

    try:
        result = register_bedrock_agent(
            manifest=manifest,
            lambda_arn=lambda_arn,
            agent_role_arn=role_arn,
            schema_s3_bucket=schema_bucket,
            schema_s3_key=_schema_key,
            foundation_model=model,
            region=region,
            create_alias=not no_alias,
            alias_name=alias,
        )

        click.echo(click.style("✓ Bedrock Agent registered successfully", fg="green"))
        click.echo()
        click.echo(f"  Bedrock Agent ID:  {result['agent_id']}")
        click.echo(f"  Agent ARN:         {result['agent_arn']}")
        click.echo(f"  Schema URI:        {result['schema_uri']}")
        if "alias_id" in result:
            click.echo(f"  Alias ID:          {result['alias_id']}")
            click.echo(f"  Alias ARN:         {result['alias_arn']}")

        click.echo()
        click.echo(click.style(
            "  Tollgate policy enforcement is active inside the Lambda —\n"
            "  Bedrock cannot bypass ERISA/DOL compliance rules.",
            fg="cyan",
        ))

    except Exception as exc:
        click.echo(click.style(f"✗ Registration failed: {exc}", fg="red"), err=True)
        sys.exit(1)


if __name__ == "__main__":
    cli()
