"""Migrated to canonical tollgate.security.encryption. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./security/encryption.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/security/encryption.py.
"""

from tollgate.security.encryption import *  # noqa: F401, F403
