"""Migrated to canonical tollgate.security.immutable_audit. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./security/immutable_audit.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/security/immutable_audit.py.
"""

from tollgate.security.immutable_audit import *  # noqa: F401, F403
