"""Migrated to canonical tollgate.integrations.mcp. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./integrations/mcp.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/integrations/mcp.py.
"""

from tollgate.integrations.mcp import *  # noqa: F401, F403
