"""Migrated to canonical tollgate.integrations.strands. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./integrations/strands.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/integrations/strands.py.
"""

from tollgate.integrations.strands import *  # noqa: F401, F403
