"""Migrated to canonical tollgate.backends.dynamodb_store. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./backends/dynamodb_store.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/backends/dynamodb_store.py.
"""

from tollgate.backends.dynamodb_store import *  # noqa: F401, F403
