"""Migrated to canonical tollgate.backends.sqs_approver. Thin re-export shim.

Foundry's vendored copy of tollgate is being eliminated as part of the
foundry → arc migration. Do not edit this file — modify
./backends/sqs_approver.py only by editing the canonical tollgate package at
agent-incubation/tollgate/src/tollgate/backends/sqs_approver.py.
"""

from tollgate.backends.sqs_approver import *  # noqa: F401, F403
