"""
RegistryCatalog — the machine-readable index of all registered agents.

The catalog is generated from the manifests in the agent-registry repo.
It is the company-wide source of truth: what agents exist, what they can do,
who owns them, what stage they are at, and whether they are active.

The catalog is typically generated by CI on every merge to agent-registry/main:

    from arc.core.registry import build_catalog
    catalog = build_catalog(registry_dir="registry/")
    catalog.save("registry.yaml")

Teams and leadership can browse the catalog:

    catalog = RegistryCatalog.load("registry.yaml")
    for agent in catalog.agents_by_stage("SCALE"):
        print(agent.agent_id, agent.owner)
"""

from __future__ import annotations

import datetime
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Iterator

import yaml

from arc.core.manifest import AgentManifest, AgentStatus, load_manifest
from arc.core.lifecycle import LifecycleStage


@dataclass
class CatalogEntry:
    """
    A single entry in the central agent registry catalog.

    Derived from AgentManifest with extra registry metadata.
    """
    agent_id: str
    version: str
    owner: str
    description: str
    lifecycle_stage: str
    status: str
    environment: str
    allowed_effects: list[str]
    data_access: list[str]
    success_metrics: list[str]
    tags: list[str]
    team_repo: str
    foundry_version: str
    registered_at: str = ""      # ISO timestamp of first registry submission
    updated_at: str = ""         # ISO timestamp of last update
    manifest_source: str = ""    # Path to manifest in registry repo

    @classmethod
    def from_manifest(
        cls,
        manifest: AgentManifest,
        manifest_source: str = "",
        registered_at: str = "",
        updated_at: str = "",
    ) -> "CatalogEntry":
        now = datetime.datetime.utcnow().isoformat() + "Z"
        return cls(
            agent_id=manifest.agent_id,
            version=manifest.version,
            owner=manifest.owner,
            description=manifest.description,
            lifecycle_stage=manifest.lifecycle_stage.value,
            status=manifest.status.value,
            environment=manifest.environment,
            allowed_effects=[e.value for e in manifest.allowed_effects],
            data_access=manifest.data_access,
            success_metrics=manifest.success_metrics,
            tags=manifest.tags,
            team_repo=manifest.team_repo,
            foundry_version=manifest.foundry_version,
            registered_at=registered_at or now,
            updated_at=updated_at or now,
            manifest_source=manifest_source,
        )

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class RegistryCatalog:
    """
    The full catalog of registered agents.

    Generated from the agent-registry repo by CI. Consumed by:
      - Leadership dashboards (what agents are live?)
      - Team discovery (what has already been built?)
      - CI validation (is this agent registered before deploying to prod?)
      - Compliance audit (what was running on date X at policy version Y?)
    """
    generated_at: str = field(default_factory=lambda: datetime.datetime.utcnow().isoformat() + "Z")
    foundry_version: str = ""
    agents: list[CatalogEntry] = field(default_factory=list)

    # ── Queries ───────────────────────────────────────────────────────────────

    def get(self, agent_id: str) -> CatalogEntry | None:
        """Return an entry by agent_id, or None."""
        return next((a for a in self.agents if a.agent_id == agent_id), None)

    def agents_by_stage(self, stage: str) -> list[CatalogEntry]:
        """Return all agents at a given lifecycle stage."""
        return [a for a in self.agents if a.lifecycle_stage == stage.upper()]

    def agents_by_owner(self, owner: str) -> list[CatalogEntry]:
        """Return all agents owned by a given team."""
        return [a for a in self.agents if a.owner == owner]

    def active_agents(self) -> list[CatalogEntry]:
        """Return all agents with status 'active'."""
        return [a for a in self.agents if a.status == AgentStatus.ACTIVE.value]

    def production_agents(self) -> list[CatalogEntry]:
        """Return all agents running in production."""
        return [a for a in self.agents if a.environment == "production" and a.status == AgentStatus.ACTIVE.value]

    def agents_with_effect(self, effect: str) -> list[CatalogEntry]:
        """Return all agents that declare a given effect."""
        return [a for a in self.agents if effect in a.allowed_effects]

    def iter_by_stage(self) -> Iterator[tuple[str, list[CatalogEntry]]]:
        """Iterate agents grouped by lifecycle stage in pipeline order."""
        stage_order = [s.value for s in LifecycleStage]
        for stage in stage_order:
            agents = self.agents_by_stage(stage)
            if agents:
                yield stage, agents

    # ── Stats ─────────────────────────────────────────────────────────────────

    def summary(self) -> dict:
        """Return a summary dict for dashboards."""
        return {
            "total": len(self.agents),
            "active": len(self.active_agents()),
            "production": len(self.production_agents()),
            "by_stage": {
                stage: len(self.agents_by_stage(stage))
                for stage in [s.value for s in LifecycleStage]
            },
            "by_status": {
                status: sum(1 for a in self.agents if a.status == status)
                for status in [s.value for s in AgentStatus]
            },
            "generated_at": self.generated_at,
        }

    # ── I/O ───────────────────────────────────────────────────────────────────

    def save(self, path: str | Path) -> None:
        """Persist the catalog to a YAML file."""
        data = {
            "generated_at": self.generated_at,
            "foundry_version": self.foundry_version,
            "summary": self.summary(),
            "agents": [a.to_dict() for a in self.agents],
        }
        Path(path).write_text(yaml.dump(data, default_flow_style=False, sort_keys=False))

    @classmethod
    def load(cls, path: str | Path) -> "RegistryCatalog":
        """Load a catalog from a YAML file."""
        with open(path) as f:
            data = yaml.safe_load(f)

        agents = [CatalogEntry(**a) for a in data.get("agents", [])]
        return cls(
            generated_at=data.get("generated_at", ""),
            foundry_version=data.get("foundry_version", ""),
            agents=agents,
        )


def build_catalog(
    registry_dir: str | Path,
    foundry_version: str = "",
) -> RegistryCatalog:
    """
    Build a RegistryCatalog by scanning a registry directory for manifests.

    Expects the registry directory to contain subdirectories, each with
    a manifest.yaml file:

        registry/
          retirement-trajectory/manifest.yaml
          fiduciary-watchdog/manifest.yaml
          ...

    Args:
        registry_dir:    Root of the registry directory.
        foundry_version: The version string recorded in the catalog.

    Returns:
        RegistryCatalog with all agents indexed.
    """
    root = Path(registry_dir)
    entries: list[CatalogEntry] = []
    errors: list[str] = []

    for manifest_path in sorted(root.rglob("manifest.yaml")):
        try:
            manifest = load_manifest(manifest_path)
            entry = CatalogEntry.from_manifest(
                manifest=manifest,
                manifest_source=str(manifest_path.relative_to(root)),
            )
            entries.append(entry)
        except Exception as e:
            errors.append(f"{manifest_path}: {e}")

    if errors:
        import warnings
        for err in errors:
            warnings.warn(f"Skipped invalid manifest: {err}", stacklevel=2)

    return RegistryCatalog(
        foundry_version=foundry_version,
        agents=entries,
    )
